### ISSUE TITLE
Looping with plotabm is really slow

### ISSUE THREAD

**Issue by MatisPatel** [JuliaDynamics/AgentsPlots.jl#16]
Hey I just returned to Agents.jl, I used it back when plot2D was a thing. 

Porting over some code I noticed it is now much slower using plotabm with the steps within an animation loop. The old way with plot2D used collected data and was much faster. With @anim and plotabm I seem to get lots of windows flashing up and read/send: No error messages which I dont quite know what they refer to. 

Is there a way to speed this up or go back to the earlier way of generating data and then making the animation?

added an example below of what I'm, trying to do.
```julia
using Plots 
using Agents
using AgentsPlots
using Random
# gr()
# Random.seed!(13)
mutable struct Individual <: AbstractAgent
    id::Int # The identifier number of the agent
    pos::Tuple{Int,Int} # The x, y location of the agent on a 2D grid
    type::Int # The group of the agent,  determines mood as it interacts with neighbors
end

space = GridSpace((10,10), moore = true, periodic = true)

model = ABM(Individual, space;
    scheduler = fastest)

for n in 1:100
    agent = Individual(n, (1,1), n)
    add_agent_single!(agent, model)
end 

function agentStep!(agent, model) 
    # get neighbors 
    neighbors = node_neighbors(agent, model) 
    # pick random neighbour 
    other = rand(neighbors)
    # Birth death or Death birth 
    if rand() < 0.5 
        victor = agent
        victim = get_node_agents(other, model)[1]
    else 
        victor = get_node_agents(other, model)[1]
        victim = agent 
    end 
    # replace victim with victor 
    #add new 
    add_agent!(victim.pos, model, victor.type)
    # remove victim 
    kill_agent!(victim, model) 
    return 
end

properties = [:pos, :type]
n = 100
# data = run!(model, agentStep!, n; adata=properties)
# plot2D(data, :type, t=3, nodesize=12)
# anim = @animate for i in 1:n
#     plot2D(data, :type, t=i, nodesize=12)
# end
indcolour(a) = a.type
# gif(anim, "neutralTest.gif", fps = 5);

anim = @animate for i in 1:n
    p1 = plotabm(
        model;
        grid=false,
        showaxis = false,
        ac = indcolour,
        am=:square
    );
    step!(model, agentStep!, 1);
end

# gif(anim, "neutral.gif", fps=3)
```

**Comment by Datseris** [comment]
Hi,

> read/send: No error messages 

This is a problem of GR and I don't think has something to do with Agents.jl. Notice that the only thing we do is call the function `scatter` from Plots.jl.

---

> With @anim and plotabm I seem to get lots of windows flashing up and read/send: No error messages which I dont quite know what they refer to.

I have personally never noticed this and we animate many things in the documentation. Can you re-install your plotting packages and try again?

---

> Is there a way to speed this up or go back to the earlier way of generating data and then making the animation?

I don't think either of these things are easy. As I mentioned above, we only call the function `scatter`, and thus any performance improvement lies outside Agents.jl. Going back is definitely not an option, since the current interface is a dramatic improvement of the previous one with 10s more features, much more flexibility, and much more.

What you should do is generate the data and then use Data Voyager or some other faster plotting framework if performance is a big concern. `plotabm` targets flexibility. Alternatively, you can wait a bit until the following PR is merged: https://github.com/JuliaDynamics/InteractiveChaos.jl/pull/7 which will provide a Makie version of the plotting (100-fold if not 1000-fold faster plotting).

**Comment by MatisPatel** [comment]
Thanks for the response. Yeah seems to e an issue with GR using Pyplot has removed that issue.

I do agree that `plotabm()` is a much nicer function. I guess what might be nice is a way to feed the dataframe from `run!()`  into a plot recipe that gives time-series data. I guess I should probably just write my own. 

Thanks for the help! I will play around with making a custom recipe.

**Comment by Datseris** [comment]
>  I guess what might be nice is a way to feed the dataframe from run!()

This seems sensible but be ware that it only makes sense if you (a) DO NOT do agent data aggregation and  (b) also save the agent positions.

>  I guess I should probably just write my own.

Feel free to contribute this to the documentation of Agents.jl, could be useful for others as well.
